// Producer reputation profiles (general critic reputation, not bottle scores)
const PRODUCER_NOTES = {
"George Roumier":["legend","One of Burgundy's most coveted domaines — Chambolle-Musigny royalty whose bottles trade far above their release price."],
"Georges de Vogue":["legend","Historic Chambolle-Musigny estate and the largest owner of the Musigny grand cru."],
"Sylvain Cathiard":["legend","Vosne-Romanée cult domaine — tiny production and stellar critic scores across the whole range."],
"Emmanuel Rouget":["legend","Nephew and heir of the legendary Henri Jayer; his Vosne-Romanée wines are collector trophies."],
"Domaine des Comtes Lafon":["legend","A reference point for Meursault and one of the greatest names in white Burgundy — the Volnay reds are superb too."],
"Domaine Leflaive":["legend","Puligny-Montrachet's most famous domaine and a biodynamic pioneer; benchmark white Burgundy."],
"Jean-Claude Ramonet":["legend","Chassagne-Montrachet royalty — the whites are consistently ranked among Burgundy's finest."],
"Jacques-Frederic Mugnier":["legend","Ethereal Chambolle-Musigny wines; Musigny and Les Amoureuses are all-time greats, and Clos de la Maréchale is superb value."],
"Dujac":["legend","Morey-Saint-Denis icon famous for whole-cluster winemaking; its crus are blue-chip collectibles."],
"Egon Muller":["legend","The master of the Scharzhofberg — widely considered the world's greatest (and most expensive) Riesling producer."],
"Conterno":["legend","Barbera d'Alba Cerretta points to Giacomo Conterno — Barolo royalty whose Monfortino is Italy's most celebrated wine."],
"Meo-Camuzet":["legend","Vosne-Romanée star with Henri Jayer heritage; domaine and négociant wines alike score at the top."],
"Domaine Meo-Camuzet":["legend","Vosne-Romanée star with Henri Jayer heritage; domaine and négociant wines alike score at the top."],
"Ponsot":["legend","Historic Morey-Saint-Denis domaine; the Clos de la Roche Vieilles Vignes is a benchmark grand cru."],
"Georges Noellat":["top","Vosne-Romanée domaine revived by Maxime Cheurlin — one of Burgundy's hottest names with critics."],
"Hubert Lignier":["top","Top Morey-Saint-Denis domaine; Clos de la Roche is the flagship."],
"Domaine de Montille":["top","Classicist Volnay/Pommard estate admired for elegant, age-worthy reds."],
"Robert Chevillon":["top","The benchmark of Nuits-Saint-Georges, with a stable of old-vine premiers crus."],
"Jean-Marie Fourrier":["top","Gevrey-Chambertin star; low-intervention wines with a devoted following."],
"Anne Gros":["top","Elegant Vosne-Romanée domaine; her Richebourg is one of the appellation's stars."],
"Fritz Haag":["top","Mosel benchmark from Brauneberg — Juffer-Sonnenuhr Rieslings score superbly nearly every vintage."],
"Zilliken":["top","Saar specialist famed for filigreed Rieslings from the Saarburger Rausch."],
"Philippe Pacalet":["top","Influential low-sulfur négociant making whole-cluster Burgundies with a cult following."],
"E. Guigal":["top","The Rhône's most famous house; its single-vineyard Côte-Rôties are 100-point legends."],
"M. Chapoutier":["top","Major biodynamic Rhône house with a string of top-scored single-parcel Hermitages."],
"Henri Boillot":["top","Polished domaine-négociant, strong in both Volnay reds and Puligny whites."],
"Jules Desjourneys":["top","Fabien Duperray's luxury Beaujolais project — old vines and Burgundian ambition, highly praised."],
"Ruinart":["top","The oldest champagne house (1729); blanc de blancs is its calling card."],
"Jayer-Gilles":["top","Hautes-Côtes domaine with a cult Echezeaux; rich, oak-marked, long-lived wines."],
"Marc Roy":["top","Small Gevrey-Chambertin domaine — Alexandrine Roy's village cuvées punch far above their level."],
"Serafin Pere & Fils":["top","Gevrey-Chambertin domaine with rich old-vine wines beloved by collectors."],
"Guiborat":["top","Rising grower in Cramant; taut, chalky blanc de blancs — Prisme is the cuvée to watch."],
"Wegeler":["top","Co-owner of the fabled Bernkasteler Doctor vineyard — classic Mosel pedigree."],
"Armand Heitz":["solid","Ambitious young Chassagne-based producer farming regeneratively."],
"Alain Michelot":["solid","Traditional Nuits-Saint-Georges domaine with well-priced premiers crus."],
"Bouchard Pere et Fils":["solid","Historic Beaune house with vast premier and grand cru holdings."],
"Domaine Arlaud":["solid","Fine Morey-Saint-Denis family domaine, biodynamically farmed."],
"Michel Magnien":["solid","Morey-Saint-Denis domaine working whole-cluster and clay-jar élevage."],
"Domaine Rollin":["solid","Reliable Pernand-Vergelesses source; Corton-Charlemagne is the peak."],
"Domaine Larue":["solid","Saint-Aubin specialist — smart-value white Burgundy."],
"Domaine Fernand & Laurent Pillot":["solid","Solid Chassagne-Montrachet family estate."],
"Philippe Bouzereau":["solid","Meursault family domaine based at Château de Cîteaux."],
"Raymond Dupont-Fahn":["solid","Tiny Meursault producer with a cult value following."],
"Jean et Sebastien Dauvissat":["solid","Small Chablis domaine (a separate estate from Vincent Dauvissat) with fine premiers crus."],
"Raoul Gautherin et Fils":["solid","Classic Chablis family domaine."],
"Domaine Vidal-fleury":["solid","The Rhône's oldest house (1781), now owned by Guigal."],
"Veuve Clicquot":["solid","Famous grande marque with a consistent, pinot-driven house style."],
"Pommery":["solid","Historic grande marque known for its vintage cuvées."],
"Baron de Ley":["solid","Modern Rioja estate; dependable reservas."],
"Fratelli Serio & Battista Borgogno":["solid","Traditional Barolo house with holdings in the Cannubi cru."],
"Lacourte-Godbillon":["solid","Quality grower in Écueil on the Montagne de Reims."],
"Roland Champion":["solid","Special Club grower with grand cru chardonnay in Chouilly."],
"Grongnet":["solid","Special Club grower from Étoges."],
"Champagne Chavost":["solid","Natural-leaning grower project from Chavot — a sommelier darling."],
"Tange-Gerard":["solid","Danish-French grower house — a Copenhagen favorite."],
"Domaine des Creisses":["solid","Languedoc value star."],
"Domaine de Cassiopee":["solid","Young Maranges domaine founded in 2020 — one of the Côte's talked-about newcomers."],
"Cassiopee":["solid","Young Maranges domaine founded in 2020 — one of the Côte's talked-about newcomers."],
"La Maison Romane":["solid","Oronce de Beler's micro-négoce — horse-ploughed parcels, natural approach."],
"Vin Noe":["solid","Small natural-leaning négoce making tension-driven Burgundies."],
"Domaine Guilhemas":["solid","Béarn stalwart (the Lapeyre/Guilhemas family)."],
"Machard de Gramont":["solid","Nuits-Saint-Georges family domaine."],
"Domaine Sebastien Magnien":["solid","Meursault-based domaine with good-value Côte de Beaune wines."],
"Rodolphl Demougeot":["solid","Meursault-based grower (Rodolphe Demougeot), good value."],
"Jacques Busin":["solid","Grower in the Verzenay grand cru."],
"Delavenne Pere et Fils":["solid","Bouzy grower — grand cru pinot noir country."],
"G. Tribaut":["solid","Family grower in Hautvillers."],
"Domaine Reverdy":["solid","Respected Sancerre family name."],
"Azienda Agricola Voerzio Alberto":["solid","Small La Morra estate — distinct from the famous Roberto Voerzio."]
};
